name: Build and Test Docker Image

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

env:
  DATE_WORKFLOW: ${{ github.run_number }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . --tag api.rutgerpronk.com:${{ env.DATE_WORKFLOW }}

      - name: Run Docker container
        run: docker run -d --name test-container api.rutgerpronk.com:${{ env.DATE_WORKFLOW }}

      - name: Wait for the container to start
        run: sleep 10 # TODO test if this is enough with failing configuration

      - name: Check container status
        run: |
          set -euo pipefail
          
          container_status=$(docker inspect -f '{{.State.Status}}' "test-container")
          container_logs=$(docker logs test-container)
          if [ "$container_status" -ne "running" ]; then
            echo "Container failed to start"
            echo $container_logs
            exit 1
          else
            echo "Container started successfully"
            echo $container_logs
          fi
